#!/usr/bin/env python3

from wordler import Wordler

w = Wordler()

while True:
    guess = input("Guess: ")
    if guess == 'answer':
        print(w.word)
        continue
    if guess == 'done':
        break
    w.guess(guess)
